/*
  +----------------------------------------------------------------------+
  | Copyright (c) 2026, Ilia Alshanetsky                                 |
  | Copyright (c) 2026, Advanced Internet Designs Inc.                   |
  +----------------------------------------------------------------------+
  | This source file is subject to the BSD 3-Clause license that is      |
  | bundled with this package in the file LICENSE.                       |
  +----------------------------------------------------------------------+
  | Author: Ilia Alshanetsky <ilia@ilia.ws>                              |
  +----------------------------------------------------------------------+
*/

#ifndef PHP_PDO_DUCKDB_INT_H
#define PHP_PDO_DUCKDB_INT_H

#include <duckdb.h>

/* zend_zval_value_name() (a value-flavoured type name: "true"/"false"/"null"/
 * "of type X") is PHP 8.3+. On 8.1/8.2 fall back to zend_zval_type_name(); the
 * only difference is a slightly coarser word in an argument-type error. */
#if PHP_VERSION_ID < 80300
# define zend_zval_value_name(zv) zend_zval_type_name(zv)
#endif

/* zend_str_has_nul_byte() is PHP 8.2+. */
#if PHP_VERSION_ID < 80200
static zend_always_inline bool zend_str_has_nul_byte(const zend_string *s)
{
	return memchr(ZSTR_VAL(s), '\0', ZSTR_LEN(s)) != NULL;
}
#endif

/* zend_register_internal_class_with_flags() is PHP 8.4+. The committed arginfo
 * (generated by a newer gen_stub) calls it unconditionally; shim it on 8.3 via
 * the older zend_register_internal_class_ex() + manual flag application. */
#if PHP_VERSION_ID < 80400
static zend_always_inline zend_class_entry *zend_register_internal_class_with_flags(
		zend_class_entry *class_entry, zend_class_entry *parent_ce, uint32_t flags)
{
	zend_class_entry *ce = zend_register_internal_class_ex(class_entry, parent_ce);
	ce->ce_flags |= flags;
	return ce;
}
#endif

/* Driver-specific PDO attributes (values must be >= PDO_ATTR_DRIVER_SPECIFIC so
 * PDO core routes them to the driver and surfaces them in driver_options).
 * Registered as PDO::DUCKDB_* class constants in MINIT. */
#define PDO_DUCKDB_ATTR_CONFIG     (PDO_ATTR_DRIVER_SPECIFIC)      /* array, connect-time */
#define PDO_DUCKDB_ATTR_UNBUFFERED (PDO_ATTR_DRIVER_SPECIFIC + 1)  /* bool, default false */

typedef struct {
	const char *file;
	int line;
	unsigned int errcode;
	char *errmsg;
} pdo_duckdb_error_info;

typedef struct {
	duckdb_database db;
	duckdb_connection conn;
	pdo_duckdb_error_info einfo;
	/* Whether the open_basedir SQL sandbox has already been applied to this
	 * handle. Persistent handles are escalated in place on reuse; they are not
	 * discarded when the request policy tightens. */
	bool external_access_disabled;
	/* Opt-in unbuffered (streaming) result mode for statements on this handle
	 * (PDO::DUCKDB_ATTR_UNBUFFERED). Default false = the materialized path. */
	bool unbuffered;
	/* PDO core re-applies constructor driver_options through set_attribute()
	 * after handle_factory. Accept DUCKDB_ATTR_CONFIG exactly for that reapply;
	 * later runtime calls cannot change an already-open DuckDB database. */
	bool config_reapply_pending;
} pdo_duckdb_db_handle;

typedef struct {
	pdo_duckdb_db_handle *H;
	duckdb_prepared_statement prepared;
	duckdb_result result;
	pdo_duckdb_error_info einfo;
	/* result holds a materialized rowset that must be destroyed */
	bool has_result;
	/* Result is read forward-only via the data-chunk API. We stream one chunk
	 * at a time; get_col reads column `cur` of the current chunk. */
	duckdb_data_chunk chunk;	/* current chunk, NULL when none is loaded */
	idx_t chunk_size;			/* rows in the current chunk */
	idx_t cur;					/* current row within the chunk (valid after a fetch) */
	idx_t col_count;			/* cached result column count */
	duckdb_type *col_types;		/* cached result column type ids */
	duckdb_logical_type *col_logical_types; /* cached result logical types */
	unsigned char *col_fast_nested; /* nested canonical strings can use the
									 * direct renderer */
	bool started;				/* has the first chunk been fetched? */
	bool done;					/* all chunks consumed */
	/* Per-execute latch. DuckDB keeps prepared-statement bindings across
	 * executes, so re-executing with fewer params would silently reuse the
	 * previous values. Cleared once per execute round — on the first EXEC_PRE
	 * bind, or in the executer when no param was bound (execute([])) — so a
	 * now-missing param surfaces instead of a stale value. */
	bool binds_cleared;
} pdo_duckdb_stmt;

extern const pdo_driver_t pdo_duckdb_driver;
extern const struct pdo_stmt_methods duckdb_stmt_methods;

/* Bulk-insert appender (driver-specific feature). */
typedef struct {
	duckdb_appender appender;
	bool closed;
	idx_t ncols;					/* appender target column count */
	duckdb_logical_type *col_types;	/* per-column target logical type, owned
										 * (NULL if ncols == 0). Used to route BLOB
										 * strings and to build nested values from
										 * PHP arrays. */
	duckdb_type *col_type_ids;		/* per-column duckdb_get_type_id(col_types[i]) */
	unsigned char *col_flags;		/* per-column fast-path flags */
	zend_object *pdo;	/* PDO object kept alive; it owns the connection */
	zend_object std;
} pdo_duckdb_appender;

extern zend_class_entry *pdo_duckdb_appender_ce;

static inline pdo_duckdb_appender *pdo_duckdb_appender_from_obj(zend_object *o)
{
	return (pdo_duckdb_appender *)((char *)o - offsetof(pdo_duckdb_appender, std));
}

zend_result pdo_duckdb_appender_minit(void);
const zend_function_entry *pdo_duckdb_get_driver_methods(pdo_dbh_t *dbh, int kind);

/* Ensure the open_basedir SQL sandbox is applied to this handle before running
 * SQL. Covers handles opened before open_basedir was tightened (their open-time
 * config didn't include the sandbox). One-time per handle. Returns false if the
 * sandbox is required but could not be applied. */
bool pdo_duckdb_enforce_sandbox(pdo_duckdb_db_handle *H);

/* Records an error against the dbh (or stmt). msg is copied; pass the message
 * obtained from duckdb_result_error()/duckdb_prepare_error() or a literal. */
extern int _pdo_duckdb_error(pdo_dbh_t *dbh, pdo_stmt_t *stmt, const char *msg, const char *file, int line);
#define pdo_duckdb_error(dbh, msg) _pdo_duckdb_error(dbh, NULL, msg, __FILE__, __LINE__)
#define pdo_duckdb_error_stmt(stmt, msg) _pdo_duckdb_error((stmt)->dbh, stmt, msg, __FILE__, __LINE__)

#endif /* PHP_PDO_DUCKDB_INT_H */
