/*
  +----------------------------------------------------------------------+
  | Copyright (c) 2026, Ilia Alshanetsky                                 |
  | Copyright (c) 2026, Advanced Internet Designs Inc.                   |
  +----------------------------------------------------------------------+
  | This source file is subject to the BSD 3-Clause license that is      |
  | bundled with this package in the file LICENSE.                       |
  +----------------------------------------------------------------------+
  | Author: Ilia Alshanetsky <ilia@ilia.ws>                              |
  +----------------------------------------------------------------------+
*/

#ifndef PHP_PDO_DUCKDB_INT_H
#define PHP_PDO_DUCKDB_INT_H

#include <duckdb.h>

/* zend_zval_value_name() (a value-flavoured type name: "true"/"false"/"null"/
 * "of type X") is PHP 8.3+. On 8.1/8.2 fall back to zend_zval_type_name(); the
 * only difference is a slightly coarser word in an argument-type error. */
#if PHP_VERSION_ID < 80300
# define zend_zval_value_name(zv) zend_zval_type_name(zv)
#endif

/* zend_str_has_nul_byte() is PHP 8.2+. */
#if PHP_VERSION_ID < 80200
static zend_always_inline bool zend_str_has_nul_byte(const zend_string *s)
{
	return memchr(ZSTR_VAL(s), '\0', ZSTR_LEN(s)) != NULL;
}
#endif

/* zend_register_internal_class_with_flags() is PHP 8.4+. The committed arginfo
 * (generated by a newer gen_stub) calls it unconditionally; shim it on 8.3 via
 * the older zend_register_internal_class_ex() + manual flag application. */
#if PHP_VERSION_ID < 80400
static zend_always_inline zend_class_entry *zend_register_internal_class_with_flags(
		zend_class_entry *class_entry, zend_class_entry *parent_ce, uint32_t flags)
{
	zend_class_entry *ce = zend_register_internal_class_ex(class_entry, parent_ce);
	ce->ce_flags |= flags;
	return ce;
}
#endif

/* Driver-specific PDO attributes (values must be >= PDO_ATTR_DRIVER_SPECIFIC so
 * PDO core routes them to the driver and surfaces them in driver_options).
 * Registered as PDO::DUCKDB_* class constants in MINIT. */
#define PDO_DUCKDB_ATTR_CONFIG     (PDO_ATTR_DRIVER_SPECIFIC)      /* array, connect-time */
#define PDO_DUCKDB_ATTR_UNBUFFERED (PDO_ATTR_DRIVER_SPECIFIC + 1)  /* bool, default false */

/* Driver error taxonomy (driver codes surfaced as PDO errorInfo[1]; the
 * SQLSTATE in errorInfo[0] follows the code: CONNECT maps to 08000, SYNTAX
 * to 42000, everything else to HY000):
 *   GENERAL   (1) default for runtime failures (also exec-time SQL errors
 *                 such as a missing table, which surface at execution, not
 *                 at parse time);
 *   CONNECT   (2) open/connect failures (handle factory, incl. refused config);
 *   SYNTAX    (3) prepare/parse failures (duckdb_prepare, statement extract);
 *   SANDBOX   (4) open_basedir sandbox denials (message text unchanged);
 *   STREAMING (5) mid-fetch / pending-stream errors (unbuffered results). */
#define PDO_DUCKDB_ERRCODE_GENERAL   1
#define PDO_DUCKDB_ERRCODE_CONNECT   2
#define PDO_DUCKDB_ERRCODE_SYNTAX    3
#define PDO_DUCKDB_ERRCODE_SANDBOX   4
#define PDO_DUCKDB_ERRCODE_STREAMING 5

typedef struct {
	const char *file;
	int line;
	unsigned int errcode;
	char *errmsg;
} pdo_duckdb_error_info;

typedef struct {
	duckdb_database db;
	duckdb_connection conn;
	pdo_duckdb_error_info einfo;
	/* Whether the open_basedir SQL sandbox has already been applied to this
	 * handle. Persistent handles are escalated in place on reuse; they are not
	 * discarded when the request policy tightens. */
	bool external_access_disabled;
	/* Copy of PG(open_basedir) taken when the sandbox was applied (NULL when
	 * unset). After escalate, DuckDB allowlists are frozen; if basedir is
	 * re-narrowed this no longer matches and enforce_sandbox fails closed.
	 * A copy rather than a hash: the compare sits on the appender's per-row
	 * gate, and strcmp is both cheaper than hashing and collision-free. */
	char *sandbox_basedir;
	/* Allocation flavour for sandbox_basedir (mirrors dbh->is_persistent, which
	 * the sandbox helpers do not otherwise have access to). */
	bool persistent;
	/* Opt-in unbuffered (streaming) result mode for statements on this handle
	 * (PDO::DUCKDB_ATTR_UNBUFFERED). Default false = the materialized path. */
	bool unbuffered;
	/* PDO core re-applies constructor driver_options through set_attribute()
	 * after handle_factory. Accept DUCKDB_ATTR_CONFIG exactly for that reapply;
	 * later runtime calls cannot change an already-open DuckDB database. */
	bool config_reapply_pending;
} pdo_duckdb_db_handle;

typedef struct _pdo_duckdb_nested_render_type {
	duckdb_type type;
	duckdb_logical_type logical_type;
	bool owns_logical_type;
	idx_t child_count;
	struct _pdo_duckdb_nested_render_type **children;
	char **child_names;
	/* ARRAY fixed element count, cached alongside the child type so the
	 * appender need not query it per row (0 when not an ARRAY). */
	idx_t array_size;
} pdo_duckdb_nested_render_type;

typedef enum {
	PDO_DUCKDB_TRANSACTION_NONE,
	PDO_DUCKDB_TRANSACTION_OPEN,
	PDO_DUCKDB_TRANSACTION_CLOSE
} pdo_duckdb_transaction_effect;

typedef struct {
	pdo_duckdb_db_handle *H;
	duckdb_prepared_statement prepared;
	duckdb_result result;
	pdo_duckdb_error_info einfo;
	/* result holds a materialized rowset that must be destroyed */
	bool has_result;
	/* Result is read forward-only via the data-chunk API. We stream one chunk
	 * at a time; get_col reads column `cur` of the current chunk. */
	duckdb_data_chunk chunk;	/* current chunk, NULL when none is loaded */
	idx_t chunk_size;			/* rows in the current chunk */
	idx_t cur;					/* current row within the chunk (valid after a fetch) */
	idx_t col_count;			/* cached result column count */
	duckdb_type *col_types;		/* cached result column type ids */
	duckdb_logical_type *col_logical_types; /* cached result logical types */
	pdo_duckdb_nested_render_type **col_nested_renderers; /* immutable type/name
									 * descriptors for direct nested rendering */
	bool started;				/* has the first chunk been fetched? */
	bool done;					/* all chunks consumed */
	/* Explicit effect for transaction control wrapped by EXPLAIN ANALYZE (whose
	 * native statement type is EXPLAIN), and for direct aliases recognized at
	 * prepare time. Applied only after native execution succeeds. */
	pdo_duckdb_transaction_effect transaction_effect;
	/* Per-execute latch. DuckDB keeps prepared-statement bindings across
	 * executes, so re-executing with fewer params would silently reuse the
	 * previous values. Cleared once per execute round — on the first EXEC_PRE
	 * bind, or in the executer when no param was bound (execute([])) — so a
	 * now-missing param surfaces instead of a stale value. */
	bool binds_cleared;
} pdo_duckdb_stmt;

extern const pdo_driver_t pdo_duckdb_driver;
extern const struct pdo_stmt_methods duckdb_stmt_methods;

typedef struct {
	duckdb_appender appender;
	bool closed;
	idx_t ncols;					/* appender target column count */
	duckdb_logical_type *col_types;	/* per-column target logical type, owned
										 * (NULL if ncols == 0). Used to route BLOB
										 * strings and to build nested values from
										 * PHP arrays. */
	duckdb_type *col_type_ids;		/* per-column duckdb_get_type_id(col_types[i]) */
	unsigned char *col_flags;		/* per-column fast-path flags */
	/* Per-column cached nested descriptors (CR-003): for nested columns the
	 * child names + child logical types (+ ARRAY size) are resolved once at
	 * appender creation so appendRow() reuses them instead of issuing
	 * duckdb_struct/list/array/map child queries per row. Scalar columns
	 * hold a leaf descriptor borrowing col_types[i] (owns_logical_type
	 * false). NULL when ncols == 0. */
	pdo_duckdb_nested_render_type **col_desc;
	/* Per-column string-cast probes (CR-007): cached prepared
	 * "SELECT CAST(? AS <T>)" statements validating string scalars before
	 * the native appender row is touched. NULL for columns needing no probe
	 * (VARCHAR/BLOB/nested/unspellable types); NULL when ncols == 0. */
	duckdb_prepared_statement *col_probes;
	zend_object *pdo;	/* PDO object kept alive; it owns the connection */
	zend_object std;
} pdo_duckdb_appender;

extern zend_class_entry *pdo_duckdb_appender_ce;

static inline pdo_duckdb_appender *pdo_duckdb_appender_from_obj(zend_object *o)
{
	return (pdo_duckdb_appender *)((char *)o - offsetof(pdo_duckdb_appender, std));
}

zend_result pdo_duckdb_appender_minit(void);
const zend_function_entry *pdo_duckdb_get_driver_methods(pdo_dbh_t *dbh, int kind);

/* Release the statement-layer thread-local caches (chunk vector cache, column
 * aux cache). Safe any time; entries regrow on next use. Called at request
 * shutdown and module shutdown so grow-only malloc'd buffers are not reported
 * as leaks. */
void pdo_duckdb_tls_caches_shutdown(void);

/* Ensure the open_basedir SQL sandbox is applied to this handle before running
 * SQL. Covers handles opened before open_basedir was tightened (their open-time
 * config didn't include the sandbox). One-time per handle. Returns false if the
 * sandbox is required but could not be applied. */
bool pdo_duckdb_enforce_sandbox(pdo_duckdb_db_handle *H);

/* Keep PDO's transaction flag aligned when SQL executes transaction control
 * outside beginTransaction()/commit()/rollBack(). */
void pdo_duckdb_apply_transaction_effect(pdo_dbh_t *dbh,
	pdo_duckdb_transaction_effect effect);

/* Drop a sticky driver error payload (errmsg + errcode). persistent matches
 * how the message was allocated (dbh vs stmt). */
void pdo_duckdb_clear_einfo(pdo_duckdb_error_info *einfo, bool persistent);

/* Records an error against the dbh (or stmt) with an explicit taxonomy code
 * (PDO_DUCKDB_ERRCODE_*); the SQLSTATE follows the code (08000 for CONNECT,
 * 42000 for SYNTAX, HY000 otherwise). msg is copied; pass the message
 * obtained from duckdb_result_error()/duckdb_prepare_error() or a literal. */
extern int _pdo_duckdb_error_with_code(pdo_dbh_t *dbh, pdo_stmt_t *stmt, unsigned int code, const char *msg, const char *file, int line);
#define pdo_duckdb_error_code(dbh, code, msg) _pdo_duckdb_error_with_code(dbh, NULL, code, msg, __FILE__, __LINE__)
#define pdo_duckdb_error_stmt_code(stmt, code, msg) _pdo_duckdb_error_with_code((stmt)->dbh, stmt, code, msg, __FILE__, __LINE__)
/* Records an error against the dbh (or stmt) with the default GENERAL code.
 * msg is copied; pass the message obtained from
 * duckdb_result_error()/duckdb_prepare_error() or a literal. */
extern int _pdo_duckdb_error(pdo_dbh_t *dbh, pdo_stmt_t *stmt, const char *msg, const char *file, int line);
#define pdo_duckdb_error(dbh, msg) _pdo_duckdb_error(dbh, NULL, msg, __FILE__, __LINE__)
#define pdo_duckdb_error_stmt(stmt, msg) _pdo_duckdb_error((stmt)->dbh, stmt, msg, __FILE__, __LINE__)

#endif /* PHP_PDO_DUCKDB_INT_H */
